# Generated by Django 5.2.8 on 2025-11-22 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Company name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('desired_position', models.CharField(db_index=True, max_length=200, verbose_name='Desired position')),
                ('location', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Location')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('salary_expectation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Expected salary')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Years of experience')),
                ('about', models.TextField(blank=True, verbose_name='About me')),
                ('is_active', models.BooleanField(default=True, verbose_name='Looking for job')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='resumes', to='api.skill')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Job title')),
                ('location', models.CharField(db_index=True, max_length=150, verbose_name='Location')),
                ('description', models.TextField(verbose_name='Description')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Responsibilities')),
                ('requirements', models.TextField(blank=True, verbose_name='Requirements')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salary from')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salary to')),
                ('currency', models.CharField(default='TJS', max_length=10, verbose_name='Currency')),
                ('show_salary', models.BooleanField(default=True, verbose_name='Show salary')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('fifo', 'FIFO / Вахта'), ('volunteer', 'Volunteering')], db_index=True, max_length=20, verbose_name='Employment type')),
                ('work_format', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('shift', 'Shift work')], db_index=True, max_length=10, verbose_name='Work format')),
                ('experience_required', models.CharField(choices=[('no_exp', 'No experience'), ('1_3', '1–3 years'), ('3_6', '3–6 years'), ('6_plus', '6+ years')], default='no_exp', max_length=10, verbose_name='Experience')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='api.company')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.vacancy')),
            ],
            options={
                'verbose_name': 'Featured vacancy',
                'verbose_name_plural': 'Featured vacancies',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Cover letter')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_sent', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='api.resume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_received', to='api.vacancy')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['location', 'employment_type', 'work_format'], name='api_vacancy_locatio_c8c18b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritevacancy',
            unique_together={('user', 'vacancy')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['vacancy', 'status'], name='api_applica_vacancy_7898f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'vacancy')},
        ),
    ]
